In [8]:
import numpy as np
import pandas as pd

In [9]:

data = {
    'X': [10, 20, np.nan, 40, 50],
    'Y': [np.nan, 25, 35, 45, 55],
    'Z': [5, 15, 25, np.nan, np.nan],
    'W': [np.nan, 12, np.nan, 42, 52]
}

df = pd.DataFrame(data)
print(df)

      X     Y     Z     W
0  10.0   NaN   5.0   NaN
1  20.0  25.0  15.0  12.0
2   NaN  35.0  25.0   NaN
3  40.0  45.0   NaN  42.0
4  50.0  55.0   NaN  52.0

In [10]:
df.isna()

       X      Y      Z      W
0  False   True  False   True
1  False  False  False  False
2   True  False  False   True
3  False  False   True  False
4  False  False   True  False

In [11]:
 df.isna().sum()

X    1
Y    1
Z    2
W    2
dtype: int64

In [12]:
df.isna().any() #to check if ANY null value is there in that COL

X    True
Y    True
Z    True
W    True
dtype: bool

In [13]:
df.dropna() #drop all the rows with null values

      X     Y     Z     W
1  20.0  25.0  15.0  12.0

In [14]:
df

      X     Y     Z     W
0  10.0   NaN   5.0   NaN
1  20.0  25.0  15.0  12.0
2   NaN  35.0  25.0   NaN
3  40.0  45.0   NaN  42.0
4  50.0  55.0   NaN  52.0

In [16]:
df.dropna(thresh=3) #if the row has more that or equal to 3 non null values, keep it

      X     Y     Z     W
1  20.0  25.0  15.0  12.0
3  40.0  45.0   NaN  42.0
4  50.0  55.0   NaN  52.0

In [17]:
#FILLING NULL VALUES
df.fillna(0)

      X     Y     Z     W
0  10.0   0.0   5.0   0.0
1  20.0  25.0  15.0  12.0
2   0.0  35.0  25.0   0.0
3  40.0  45.0   0.0  42.0
4  50.0  55.0   0.0  52.0

In [20]:
values = {'X':10, 'Y':20, 'Z':30, 'W':40}
df.fillna(value=values) #Add Coloumn wise Specific values to the NULL VALUES

      X     Y     Z     W
0  10.0  20.0   5.0  40.0
1  20.0  25.0  15.0  12.0
2  10.0  35.0  25.0  40.0
3  40.0  45.0  30.0  42.0
4  50.0  55.0  30.0  52.0

In [21]:
df.fillna(df.mean())

      X     Y     Z          W
0  10.0  40.0   5.0  35.333333
1  20.0  25.0  15.0  12.000000
2  30.0  35.0  25.0  35.333333
3  40.0  45.0  15.0  42.000000
4  50.0  55.0  15.0  52.000000