In [6]:
import numpy as np
import pandas as pd

In [7]:
labels = ['A', 'B','C']
my_list = [10, 20, 30]
arr = np.array([1,2,3])
d = {1:20, 3 :20, 2:30}

In [10]:
s = pd.Series(my_list, index = labels)

In [11]:
print(s)

A    10
B    20
C    30
dtype: int64

In [12]:
pd.Series(arr, index = labels)

A    1
B    2
C    3
dtype: int64

In [13]:
pd.Series(d)

1    20
3    20
2    30
dtype: int64

In [14]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda', 'David', 'Sophia'],
    'Age': [28, 34, 29, 42, 25, 31],
    'City': ['New York', 'Paris', 'Berlin', 'London', 'Tokyo', 'Sydney'],
    'Salary': [65000, 70000, 62000, 85000, 55000, 78000]
}

In [16]:
df = pd.DataFrame(data)

In [17]:
df

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3   Linda   42    London   85000
4   David   25     Tokyo   55000
5  Sophia   31    Sydney   78000

In [18]:
df["Name"]

0      John
1      Anna
2     Peter
3     Linda
4     David
5    Sophia
Name: Name, dtype: object

In [21]:
df[["Name", "Age"]]

     Name  Age
0    John   28
1    Anna   34
2   Peter   29
3   Linda   42
4   David   25
5  Sophia   31

In [22]:
df["Designation"] =["Engineer","Doctor","Engineer","Doctor","Engineer","Doctor"] #Add a new Coloum

In [23]:
df

     Name  Age      City  Salary Designation
0    John   28  New York   65000    Engineer
1    Anna   34     Paris   70000      Doctor
2   Peter   29    Berlin   62000    Engineer
3   Linda   42    London   85000      Doctor
4   David   25     Tokyo   55000    Engineer
5  Sophia   31    Sydney   78000      Doctor

In [25]:
df.drop("Designation", axis = 1) # By Default axis = 0, row wise ->

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3   Linda   42    London   85000
4   David   25     Tokyo   55000
5  Sophia   31    Sydney   78000

In [26]:
df #only temp/ for view deletion, no removal from main data.

     Name  Age      City  Salary Designation
0    John   28  New York   65000    Engineer
1    Anna   34     Paris   70000      Doctor
2   Peter   29    Berlin   62000    Engineer
3   Linda   42    London   85000      Doctor
4   David   25     Tokyo   55000    Engineer
5  Sophia   31    Sydney   78000      Doctor

In [27]:
df.drop('Designation', axis = 1 , inplace = True) # For Permanent Deletion, use INPLACE = TRUE

In [28]:
df

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3   Linda   42    London   85000
4   David   25     Tokyo   55000
5  Sophia   31    Sydney   78000

In [29]:
df.drop(['Age', 'City'], axis = 1) # for multi-col removal, use []

     Name  Salary
0    John   65000
1    Anna   70000
2   Peter   62000
3   Linda   85000
4   David   55000
5  Sophia   78000

In [31]:
df.loc[0] # Selecting Rows

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [32]:
df.loc[[0,3]]

    Name  Age      City  Salary
0   John   28  New York   65000
3  Linda   42    London   85000

In [34]:
df.loc[[0,1,2]][["Name","Age"]] # Specific Col of Specific Rows

    Name  Age
0   John   28
1   Anna   34
2  Peter   29

In [35]:
#Selecting People Whose Age > 30
df[df["Age"]>30]

     Name  Age    City  Salary
1    Anna   34   Paris   70000
3   Linda   42  London   85000
5  Sophia   31  Sydney   78000

In [37]:
#Selecting People Whose Age > 30 and City = Paris
df[(df["Age"]>30) & (df["City"] == "Paris")]  #while using multiple & or | operations, use ()

   Name  Age   City  Salary
1  Anna   34  Paris   70000