In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.DataFrame({'A':[10,20,30,40,50], 'B' :[1,2,3,4,5], 'C':[67,70,80,90,100]})
df

    A  B    C
0  10  1   67
1  20  2   70
2  30  3   80
3  40  4   90
4  50  5  100

In [7]:
df.shape

(5, 3)

In [8]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [10]:
df.describe()

               A         B           C
count   5.000000  5.000000    5.000000
mean   30.000000  3.000000   81.400000
std    15.811388  1.581139   13.776792
min    10.000000  1.000000   67.000000
25%    20.000000  2.000000   70.000000
50%    30.000000  3.000000   80.000000
75%    40.000000  4.000000   90.000000
max    50.000000  5.000000  100.000000

In [11]:
df['A'] + 10

0    20
1    30
2    40
3    50
4    60
Name: A, dtype: int64

In [12]:
def square(x):
    return x**2

In [14]:
df['B'].apply(square)   #applying a function

0     1
1     4
2     9
3    16
4    25
Name: B, dtype: int64

In [15]:
#to make it inplace

In [16]:
df['B']= df['B'].apply(square)

In [17]:
df

    A   B    C
0  10   1   67
1  20   4   70
2  30   9   80
3  40  16   90
4  50  25  100

In [18]:
df['Z']= df['B'].apply(square) #making a new col
df

    A   B    C    Z
0  10   1   67    1
1  20   4   70   16
2  30   9   80   81
3  40  16   90  256
4  50  25  100  625